### ISSUE TITLE
W/KeyStore: KeyStore exception     android.os.ServiceSpecificException:

### ISSUE THREAD

**Issue by vanillazz** [ophio/secure-preferences#28]
Hello, i got this error when try to get secret key from key generator..
it happens when run on android Pie..
Anyone got the same problem? is there any update for this..?

`W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at in.co.ophio.secure.vault.SecretKeyWrapper.<init>(SecretKeyWrapper.java:66)
        at in.co.ophio.secure.core.KeyStoreKeyGenerator.loadOrGenerateKeys(KeyStoreKeyGenerator.java:66)
        at in.co.ophio.secure.core.KeyStoreKeyGenerator.<init>(KeyStoreKeyGenerator.java:46)
        at in.co.ophio.secure.core.KeyStoreKeyGenerator.get(KeyStoreKeyGenerator.java:56)`

**Comment by joelpou** [comment]
Is there any support whatsoever for this repo? I can't find a way to solve this issue.
